### ISSUE TITLE
Add skeleton / boilerplate for creating a react app

### ISSUE THREAD

**Issue by gcorne** [HubSpot/hubspot-cms-tools#12]
Basically add `hs create react-app`.

**Comment by levinkeo** [comment]
@anthmatic and I have chatted a bit about the benefits of having both a "template" and "module" boilerplate in that it keeps each example approach as simple and repurpos-able as possible. 

Depending on what container (template, partial, or module) you'd like to use for your app, the project structure and implementation method is going to differ, especially if you're looking to initialize your app with server-side rendered markup (HubL in this case).

I'm curious what @williamspiro and @iamw11y think about a two skeleton/boilerplate approach here (for now, I'm thinking `module` and `template`), and if you're on-board, how that distinction should be made in the `hs create` command (flags, initiate a prompt with multiple choice, etc.).

**Comment by gcorne** [comment]
@levinkeo do you have ideas for the name used when running `hs create`? Is the idea that we would have a prompted flow?

**Comment by levinkeo** [comment]
I'm open to anything that allows for future flexibility in both framework (`react` / `vue` etc) and output type / container (`module` / `template` / `?`), but something like this would make sense to me for a prompt:
```bash
$ hs create react-app
  type:
  * module
    template
```

Open to flags / arguments too, it's more the order of `hs create <app+framework> <output type>` that I think makes sense.

**Comment by iamw11y** [comment]
> I'm curious what @williamspiro and @iamw11y think about a two skeleton/boilerplate approach here

I think the two skeleton/boilerplate approach makes sense given the differences depending on what container is used. I wouldn't go as far as different command arguments (e.g., `hs create react-app-module` and `hs create react-app-template`), though, so we can then consider the next part of the question...

> and if you're on-board, how that distinction should be made in the `hs create` command (flags, initiate a prompt with multiple choice, etc.).

It's worth considering this in a larger discussion about our CLI best practices. It would be great to provide power users with succinct commands for achieving a desired result (e.g., flag/argument formats like `hs create app --framework=react --container=module` or `hs create app -f react -c module`), but to provide prompted commands that allow us to include additional guidance for developers who want/need that. If it's possible to implement both without undue effort, that would be ideal, but in the case of boilerplate anything (themes, apps, etc.) I'd lean toward the latter because the associated `create` commands strike me as applying more to developers that might appreciate the guidance. So in this case, the prompted flow @levinkeo outlined above makes most sense to me.

**Comment by anthmatic** [comment]
@iamw11y I think that adding flags and prompts should be pretty straight forward.

In #201 I added `hs create react-app` but I'm happy to simplify that to just `hs create app`

**Comment by iamw11y** [comment]
@anthmatic I'm fine with `hs create react-app`...but used `hs create app -f react` in my example as a way of highlighting how we might tackle commands with both command arguments and (multiple) flag arguments. I didn't mean to imply that we'd consider other frameworks (e.g., Vue or Angular) for these apps, but if that's something that's on our radar, then it may be worth building that in now so we don't have multiple similar commands (e.g., `hs create react-app` and `hs create vue-app`) or force ourselves into a scenario of deprecating an existing command in favor of a more flexible one somewhere down the road, which would add friction to the developer experience.

**Comment by gcorne** [comment]
> I didn't mean to imply that we'd consider other frameworks (e.g., Vue or Angular) for these apps, but if that's something that's on our radar, then it may be worth building that in now so we don't have multiple similar commands (e.g., hs create react-app and hs create vue-app) or force ourselves into a scenario of deprecating an existing command in favor of a more flexible one somewhere down the road, which would add friction to the developer experience.

I don't think there is a huge concern when it comes to deprecating or removing project types from `hs create` because `hs create` for projects is not a frequent activity and not on the critical path.
