### ISSUE TITLE
Discuss config ordering

### ISSUE THREAD

**Issue by miketalley** [HubSpot/hubspot-cms-tools#195]
Related to https://github.com/HubSpot/hubspot-cms-tools/pull/184#discussion_r417614315 and how all of the portal configs are getting their attributes reordered for consistency. 

Do we want keep doing this, or only reorder the portal config that is being modified?

**Comment by gcorne** [comment]
My take on this is that we treat the configuration file as if it is owned by the user and only update what is necessary when a user runs a command like `hs auth`. @williamspiro @iamw11y any thoughts on this?

**Comment by williamspiro** [comment]
I agree 👍 IMO, the less we update user files automagically, the less likely a user will find themselves wondering if they can trust the CLI.

**Comment by iamw11y** [comment]
I also agree. If we're modifying only what's necessary, based on user-run commands, then the mental model will remain intact. The user will rightly think, "If I do this, the associated code will be updated like that." Otherwise, updating configs outside the expected range will cause users to question what other changes might occur when they interact with the tools, leading to confusion and a loss of confidence or trust in the system we've built.
