### ISSUE TITLE
Error Validating Template: Unrecognized field "left"

### ISSUE THREAD

**Issue by jplew** [HubSpot/hubspot-cms-tools#268]
Hello,

all my pages in production went blank today for no apparent reason. Here is an example: **https://fau.cannabisstudiesonline.com/home-1**

I attempted to debug the issue by redeploying my code using `hs watch`, and received the following output:

![Screenshot from 2020-07-30 13-56-14](https://user-images.githubusercontent.com/462836/88989478-5bf9ab00-d2f9-11ea-9dff-6f53ef558457.png)

After deleting the `left` and `right` properties in all my templates, I was able to restore the pages back to their original state. For example: https://fau.cannabisstudiesonline.com

![image](https://user-images.githubusercontent.com/462836/88990465-9fedaf80-d2fb-11ea-8a41-bdc795a16089.png)

Can anyone tell me why the `left` and `right` fields are now unrecognized on the padding object? Also, why should their inclusion completely break the page layout? They are documented as valid right here: https://developers.hubspot.com/docs/cms/hubl/tags/dnd-areas#drag-and-drop-section-code-dnd-section-code-

What is more, they were working just fine until about twelve hours ago, when everything suddenly went to hell. We have over six mission-critical domains based on the same template, generating thousands of dollars of revenue daily. All of them went down simultaneously. My suspicion is that some breaking changes were released on the backend without notice. I'm hoping for some confirmation from your end before my ass gets fired for incompetence. 

I'm pretty sure the HTML validation tool runs on the backend, not in the CLI, but I was hoping to get an answer directly from someone on your dev team. So far, support has been spectacularly unhelpful. Thanks.

**Comment by mattcoley** [comment]
The issue is with the margin not the padding. Margin only supports `top`/`bottom`, not `left`/`right`. I removed the left/right references in the margin and republished your template and it appears the page is back. I am digging into the code to understand why the template would break with some bad input data like this since the parsing should be forgivable, however something must have changed recently. I will update here when I find the root cause.

**Comment by mattcoley** [comment]
Update on our end: we were trying to roll out a change to improve padding/margin in the editors, however there was a mistake in the code where using invalid properties like these would cause a fatal error whereas before they would just be a warning. Unfortunately our pre-deploy tests did not catch this issue. The underlying issue is fixed and we are looking into improvements in our pre-deploy tests.

**Comment by jplew** [comment]
Hi Matt, thanks for the update, appreciate your help.
