### ISSUE TITLE
Switch over to using "account" and "accounts" instead of portal(s)

### ISSUE THREAD

**Issue by gcorne** [HubSpot/hubspot-cms-tools#68]
To be consistent with recommended HubSpot terminology, we need to move away from "portal" and "portals" and instead use "account" and "accounts" everywhere. We should do this such that when upgrading users don't need to modify existing config files, scripts, or commands, so `--account` will have an alias of `--portal` and both `accounts` and `portals` will need to be supported in the config file.

**Comment by TheWebTech** [comment]
Just adding a [recent example](https://hubspotdev.slack.com/archives/CLJJXGTC0/p1591096596430800) of where this has caused developer confusion and trouble.

Our [developer written style guide](https://docs.google.com/document/d/1dAv5penw5OYRhrZEjhcspsmCSjtv5RUQGMhGGeDeK-0/edit#heading=h.l4voh9yrmci2) encourages using the term account rather than portal.

[HubSpot written style guide](https://wiki.hubspotcentral.net/pages/viewpage.action?pageId=36308094#HubSpotWrittenStyleGuide-ReferringtoHubSpotSoftwareinGeneral) encourages using account, discourages portal.

Our docs can explain that portal == HubSpot Account better in the short term, though explaining this adds a layer of "weird stuff" and encourages both HubSpotters and external developers to perpetuate the term portal which may confuse new developers.
